#!/bin/bash
[ $# -ge 1 ] || { echo "usage: $0 <table> [<append:0|1>] [<dagdir>] [<test_num>...]" 1>&2; exit 1; }

csv="$1"
shift

append="${1:-1}"
shift

dagdir="$1"
if [ -n "$dagdir" ]; then
  shift
else
  dagdir="dag"
fi

tests=($@)
[ ${#tests[@]} -gt 0 ] || tests=({1..225})

if [[ $append == false ]] || [[ $append == no ]] || [[ $append == 0 ]]; then
  echo "Test,CPU Time [min],Runtime [min]" > "$csv"
fi
for i in ${tests[@]}; do
  name=test_$(printf %03d $i)
  echo "$name: compute average runtime of individual registrations"
  # average CPU time
  n=0
  cpu_time=0
  for row in $(grep 'CPU time is ' "$dagdir/$name/register_images/"*/reg_*.log | cut -d: -f2 | sed -r 's/CPU time is +([[:digit:]]+) h +([[:digit:]]+) min +([[:digit:]]+) sec/\1,\2,\3/'); do
    IFS=',' read -ra cols <<< "$row"
    let cpu_time="$cpu_time + ${cols[0]} * 3600 + ${cols[1]} * 60 + ${cols[2]}"
    let n++
  done
  cpu_time=$(/usr/bin/bc -l <<< "$cpu_time / ($n * 60.0)")
  # average wall time
  n=0
  wall_time=0
  for row in $(grep 'Finished in ' "$dagdir/$name/register_images/"*/reg_*.log | cut -d: -f2 | sed -r 's/Finished in +([[:digit:]]+) h +([[:digit:]]+) min +([[:digit:]]+) sec/\1,\2,\3/'); do
    IFS=',' read -ra cols <<< "$row"
    let wall_time="$wall_time + ${cols[0]} * 3600 + ${cols[1]} * 60 + ${cols[2]}"
    let n++
  done
  wall_time=$(/usr/bin/bc -l <<< "$wall_time / ($n * 60.0)")
  # print output table row
  printf "%d,%6.2f,%6.2f\n" $i $cpu_time $wall_time >> "$csv"
done
