#!/bin/bash
[ $# -ge 1 ] || { echo "usage: $0 <table> [<append:0|1>] [<outdir> <test_id>...|<csvdir>]" 1>&2; exit 1; }

table="$1"
shift

append="${1:-1}"
shift

outdir="${1:-$PWD}"
shift

tests=($@)
[ ${#tests[@]} -gt 0 ] || tests=(0)

for i in ${tests[@]}; do
  if [ $i -eq 0 ]; then
    name=
    csvdir="$outdir"
  else
    name=$(printf 'test_%03d' $i)
    csvdir="$outdir/$name/overlap"
  fi
  avgcsv="$csvdir/average.csv"
  if [ ! -f "$avgcsv" ]; then
    [ -z "$name" ] || echo "$name: compute average of individual pairwise overlaps"
    csvlst=($(find "$csvdir" -name '*.csv' -type f))
    if [ ${#csvlst[@]} -gt 0 ]; then
      mirtk average-overlap "${csvlst[@]}" \
          --measure DSC \
          --segment BG 84 \
          --segment CSF 83 \
          --segment WM 51..82 \
          --segment cGM 5..16 20..39 \
          --segment dGM 40..48 85 86 87 \
          --segment CC 48 \
          --segment BS+CB 17 18 19 \
          --segment Amygdala+Hippocampus 1..4 \
          --segment Ventricles 49 50 \
          --output  "$avgcsv"
      [ $? -eq 0 ] || exit 1
    else
      echo "Could not find any CSV files in $csvdir" 1>&2
      exit 1
    fi
  fi
done

segments=('BG' 'CSF' 'WM' 'cGM' 'dGM' 'CC' 'BS+CB' 'Amygdala+Hippocampus' 'Ventricles')
if [[ $append == false ]] || [[ $append == no ]] || [[ $append == 0 ]]; then
  if [ ${#tests[@]} -gt 1 -o ${tests[0]} -ne 0 ]; then
    echo -n "Test" > "$table" || exit 1
    c=1
  else
    rm -f "$table" || exit 1
    c=0
  fi
  for segment in "${segments[@]}"; do
    [ $c -eq 0 ] || echo -n ',' >> "$table"
    echo -n "$segment" >> "$table"
    let c++
  done
  echo >> "$table"
fi
for i in ${tests[@]}; do
  if [ $i -eq 0 ]; then
    avgcsv="$outdir/average.csv"
    c=0
  else
    echo -n "$i" >> "$table"
    avgcsv="$(printf "$outdir/test_%03d/overlap/average.csv" $i)"
    c=1
  fi
  for segment in "${segments[@]}"; do
    dice=$(grep "^$segment," "$avgcsv" | cut -d, -f2)
    [ $? -eq 0 ] || { echo "Segment $segment row not found in '$avgcsv'" 1>&2; exit 1; }
    [ $c -eq 0 ] || echo -n ',' >> "$table"
    echo -n "$dice" >> "$table"
    let c++
  done
  echo >> "$table"
done
