#!/bin/bash

top="$(cd "$(dirname "$BASH_SOURCE")/../.." && pwd)"
dag="${1:-"$top/dag/dHCP275/adaptive-sigma_1.00-ffd/def_alignment.dag"}"

dag_name="$(basename "$dag")"
dag_name="${dag_name/.dag/}"

log="$2"
if [ -z "$log" ]; then
  log="$(dirname "$dag")"
  log="${log/\/dag\//\/log\/}"
  log="$log/${dag_name}_1.log"
fi

info()
{
  echo "$(date '+%d/%m/%y %H:%M:%S'): $@"
}

try=$(basename "$log" | sed 's/^.*_\([0-9][0-9]*\)\.log$/\1/g')
while [ $try -lt 10 ]; do
  if [ ! -f "${dag}.lock" ]; then
    grep "DAG status: 1 (DAG_STATUS_ERROR)" "$log"
    if [ $# -eq 0 ]; then
      grep "ProcessLogEvents() returned false" "$log"
      if [ $# -eq 0 ]; then
        grep "Writing Rescue DAG" "$log"
        if [ $# -eq 0 ]; then
          let next_try=try+1
          log=${log/_${try}.log/_${next_try}.log}
          try=$next_try
          lib/tools/submit-dag-to-condor -d "$dag" -l "$log"
          if [ $# -eq 0 ]; then
            info "Resubmitted DAGMan job, no. of resubmissions = $try"
          else
            info "Failed to resubmit DAGMan job, aborting..."
            exit 1
          fi
        else
          info "DAG status 1 but no rescue file written it seems, aborting..."
          exit 1
        fi
      else
        info "DAGMan status 1, but no 'ProcessLogEvents() returned false' error message in log file, aborting..."
        exit 1
      fi
    else
      info "DAGMan lock file not found, no DAG_STATUS_ERROR in log. Assumeing its finished fine"
      break
    fi
  else
    info "DAGMan lock file still exists, assuming its running fine"
  fi
  sleep 600
done
